@startuml

interface DocumentNode<VisitorType>{
{abstract} accept(VisitorType)
}
interface DocumentArray<VisitorType>{
getValueList()
getValue(index)
}
interface DocumentObject<VisitorType>{
getKeyValueMap()
get(key)
hasKey(key)
}
interface DocumentValue<VisitorType>{
}

DocumentNode <|-- DocumentArray
DocumentNode <|-- DocumentObject
DocumentNode <|-- DocumentValue

DocumentArray <|-- DynamodbList
DocumentArray <|-- DynamodbStringSet
DocumentObject <|-- DynamodbObject
DocumentValue <|-- DynamodbString
DocumentValue <|-- DynamodbNumber

class DynamodbList{
accept(DynamodbVisitor)
}

class DynamodbStringSet{
accept(DynamodbVisitor)
}

class DynamodbObject{
accept(DynamodbVisitor)
}

class DynamodbString{
accept(DynamodbVisitor)
}

class DynamodbNumber{
accept(DynamodbVisitor)
}

@enduml