@startuml

interface  ColumnMapping <<interface>> {
+{abstract} getExasolColumnName()
+{abstract} getExasolDataType()
+{abstract} getExasolDefaultValue()
+{abstract} isExasolColumnNullable()
+{abstract} accept(ColumnMappingVisitor)
}


interface  PropertyToColumnMapping <<interface>> {
+{abstract} pathToSourceProperty()
+{abstract} lookupFailBehaviour()
+accept(ColumnMappingVisitor)
}

ColumnMapping <|-- PropertyToColumnMapping
@enduml
