@startuml
!include mappingDefinitionInterface.puml

class SchemaMapping{

}

class TableMapping {
exasolName
remoteName
pathInRemoteTable
}


SchemaMapping "1" *- "*" TableMapping: tables
TableMapping "1" *- "*" ColumnMapping: columns

@enduml 

