@startuml
class SchemaMappingDefinition{

}

class TableMappingDefinition {
exasolName
remoteName
pathInRemoteTable
}

interface ColumnMappingDefinition{
getExasolColumnName()
getExasolDataType()
getExasolDefaultValue()
isExasolColumnNullable()
getLookupFailBehaviour()
getPathToSourceProperty()
}


abstract class AbstractColumnMappingDefinition {
...
}

class ToStringColumnMappingDefinition {
...
}

class ToJsonColumnMappingDefinition {
...
}


SchemaMappingDefinition "1" *- "*" TableMappingDefinition: tables
TableMappingDefinition "1" *- "*" ColumnMappingDefinition: columns
ColumnMappingDefinition <|-- AbstractColumnMappingDefinition
AbstractColumnMappingDefinition <|-- ToStringColumnMappingDefinition
AbstractColumnMappingDefinition <|-- ToJsonColumnMappingDefinition
@enduml 

