@startuml
class SchemaMappingDefinition{

}

class TableMappingDefinition {
destinationName
isRootTable
}

abstract class AbstractColumnMappingDefinition {
destinationName
pathToSourceProperty: DynamodbResultWalker
lookupFailBehaviour
}

class ToStringColumnMappingDefinition {
destinationStringSize
overflowBehaviour
}

class ToJsonColumnMappingDefinition {

}


SchemaMappingDefinition "1" *-- "*" TableMappingDefinition: tables
TableMappingDefinition "1" *-- "*" AbstractColumnMappingDefinition: columns
AbstractColumnMappingDefinition <|-- ToStringColumnMappingDefinition
AbstractColumnMappingDefinition <|-- ToJsonColumnMappingDefinition
@enduml 

