@startuml

object ":SchemaMappingDefinition" as schema{

}

object "books :TableMappingDefinition" as books{
exasolName: "BOOKS"
remoteName: "books"
pathInRemoteTable: /
}
object "booksTopics :TableMappingDefinition" as tableTopics{
exasolName: "BOOKS_TOPICS"
remoteName: "books"
pathInRemoteTable: /topics
}

schema --> books
schema --> tableTopics
@enduml
