@startuml
left to right direction

class ColumnValueExtractorFactory{
+ getValueExtractorForColumn(ColumnMapping): ColumnValueExtractor
}

interface  PropertyToColumnValueExtractorFactory <<interface>> {
+ getValueExtractorForColumn(PropertyToColumnMapping): ColumnValueExtractor
}

@enduml
