sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
      - udf_coverage
build:
  # UDFs in Exasol 7.1 require Ubuntu 20.04
  runnerOs: ubuntu-20.04
  exasolDbVersions:
    - "8.31.0" # Tests fail with 8.32.0, see https://github.com/exasol/virtual-schema-common-document/issues/193
    - "7.1.30"
