error-tags:
  VSDY:
    packages:
      - com.exasol.adapter.dynamodb
      - com.exasol.adapter.document.documentfetcher.dynamodb
      - com.exasol.adapter.document.documentnode.dynamodb
      - com.exasol.adapter.document.dynamodbmetadata
      - com.exasol.adapter.document.literalconverter.dynamodb
      - com.exasol.dynamodb
    highest-index: 34
